$(warning $(OPENCV4_VERSION))
OPENCV4_VERSION_ORIGIN := $(OPENCV4_VERSION)
ifeq ($(BR2_PACKAGE_IMX_GPU_VIV),y)
OPENCV4_VERSION := 4.5.2_imx
OPENCV4_SITE = git://source.codeaurora.org/external/imx/opencv-imx.git
OPENCV4_SITE_METHOD = git
BR_NO_CHECK_HASH_FOR += $(OPENCV4_SOURCE)
OPENCV4_OVERRIDE_SRCDIR = $(OPENCV4_DL_DIR)/git
endif

define OPENCV4_LINK_PKGDIR
ln -s $(BUILD_DIR)/opencv4-$(OPENCV4_VERSION_ORIGIN) $(BUILD_DIR)/opencv4-$(OPENCV4_VERSION)
endef

ifneq ($(OPENCV4_VERSION),$(OPENCV4_VERSION_ORIGIN))
OPENCV4_PRE_EXTRACT_HOOKS += OPENCV4_LINK_PKGDIR
endif

ifeq ($(BR2_PACKAGE_HAS_LIBOPENVX),y)
OPENCV4_CONF_OPTS += \
	-DWITH_OPENVX=ON 
endif

ifeq ($(BR2_PACKAGE_HAS_LIBOPENCL),y)
OPENCV4_CONF_OPTS += \
	-DWITH_OPENCL=ON 
endif
